{
  "hash": "9fc919d5877ee3d548168317a796a92a",
  "result": {
    "markdown": "---\ntitle: \"Deprivation in Ayr Town Centre\"\nsubtitle: \"SIMD 2020v2 Analysis at Datazone Level\"\nformat:\n  html:\n    embed-resources: true\n    toc: true\n    toc-depth: 3\n    fig-width: 10\n    fig-height: 8\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n## Introduction\n\nThe **Scottish Index of Multiple Deprivation** (SIMD 2020v2) [@scotgov2020simd] is the Scottish Government's official measure of area-level deprivation. It combines 7 domains --- Income, Employment, Health, Education, Access to Services, Crime, and Housing --- into a single overall ranking of all 6,976 datazones in Scotland. A datazone is a small area geography containing roughly 500--1,000 residents.\n\nThis analysis examines deprivation patterns **at datazone level** in and around Ayr town centre. Rather than treating South Ayrshire as a single unit (as in the [demographic comparison](demographic-comparison.qmd)), we look at variation *within* the area --- identifying which streets and neighbourhoods face the most concentrated disadvantage, which domains drive that disadvantage, and whether deprivation clusters spatially.\n\nThe study area tiers were defined by Ian MacLeod, community councillor for Ayr, based on local knowledge of how the town centre functions in practice.\n\n## Study area\n\n\n::: {.cell}\n::: {.cell-output-display}\n![South Ayrshire datazones classified into three tiers. Town Centre (red) = the core walkable retail/hospitality zone. Wider Ayr (pink) = the natural catchment area for Ayr town centre. Grey = rest of South Ayrshire.](simd-ayr-town-centre_files/figure-html/study-area-map-1.png){width=1500}\n:::\n:::\n\n\nThe three tiers are:\n\n- **Town Centre** (2 datazones): The core of Ayr's retail and hospitality area, defined by walking proximity from parking --- the area where parking puts you within 3--4 minutes' walk of shops. Beyond this boundary, the character shifts to residential \"dormitory\" streets separated by fast traffic roads with few pedestrian crossings.\n\n- **Wider Ayr** (52 datazones): The natural catchment area whose residents would gravitate to Ayr town centre rather than Prestwick's competing high street to the north. This includes areas south of the River Ayr (by proximity) and north-eastern deprived areas whose residents are more bus-dependent.\n\n- **Rest of South Ayrshire** (99 datazones): The remainder of the council area, including Prestwick, Troon, Maybole, and rural areas.\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Summary statistics by study area tier (rank 1 = most deprived nationally)\n\n|focus_tier             | Datazones| Population| Working Age| Mean SIMD Rank| Median SIMD Rank| Mean Decile|\n|:----------------------|---------:|----------:|-----------:|--------------:|----------------:|-----------:|\n|Town Centre            |         2|       1620|        1088|           1104|           1104.0|         2.5|\n|Wider Ayr              |        52|      37913|       22764|           3128|           2821.5|         5.0|\n|Rest of South Ayrshire |        99|      73147|       43332|           3650|           3137.0|         5.7|\n:::\n:::\n\n\n## Overall deprivation\n\n### Choropleth: SIMD decile across Wider Ayr\n\n\n::: {.cell}\n::: {.cell-output-display}\n![SIMD 2020v2 decile by datazone, zoomed to the Wider Ayr study area. Decile 1 (dark red) = among the 10% most deprived datazones in Scotland. Bold red outlines mark the town centre datazones.](simd-ayr-town-centre_files/figure-html/decile-choropleth-zoomed-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![SIMD 2020v2 decile across all of South Ayrshire, providing wider context.](simd-ayr-town-centre_files/figure-html/decile-choropleth-full-1.png){width=1500}\n:::\n:::\n\n\n### National context\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of all 6,976 SIMD ranks nationally. Red marks show where Ayr's wider study area datazones fall. Marks clustered to the left indicate datazones that are among the most deprived in Scotland.](simd-ayr-town-centre_files/figure-html/national-context-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Town centre datazones: SIMD 2020v2 detail\n\n|Datazone  |Name                                   |Intermediate Zone                 | Population| Working Age| SIMD Rank (/6976)| Decile|\n|:---------|:--------------------------------------|:---------------------------------|----------:|-----------:|-----------------:|------:|\n|S01012481 |Ayr South Harbour and Town Centre - 02 |Ayr South Harbour and Town Centre |        818|         570|              1486|      3|\n|S01012483 |Ayr South Harbour and Town Centre - 04 |Ayr South Harbour and Town Centre |        802|         518|               722|      2|\n:::\n:::\n\n\n## Domain profiles\n\nThe overall SIMD rank combines seven constituent domains. Different areas can have the same overall deprivation level but for very different reasons --- a town centre might score poorly on Crime and Housing but well on Access to Services, while a rural area might show the reverse pattern. Understanding *which* domains drive deprivation is critical for targeting interventions.\n\n### Faceted domain maps\n\n\n::: {.cell}\n::: {.cell-output-display}\n![SIMD 2020v2 domain ranks converted to deciles, mapped across the Wider Ayr study area. Each panel shows one of the seven domains. Domain decile 1 (dark red) = among the 10% most deprived nationally for that domain.](simd-ayr-town-centre_files/figure-html/domain-facets-1.png){width=1800}\n:::\n:::\n\n\n### Domain comparison across tiers\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Mean domain rank by study area tier. Lower values = more deprived. The Town Centre and Wider Ayr areas show markedly lower ranks (greater deprivation) than the rest of South Ayrshire across most domains.](simd-ayr-town-centre_files/figure-html/domain-profile-chart-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Mean domain rank by tier (lower = more deprived; national midpoint = 3,488)\n\n|Domain              | Town Centre| Wider Ayr| Rest of SA|\n|:-------------------|-----------:|---------:|----------:|\n|Income              |        1296|      3023|       3659|\n|SIMD2020 Employment |         954|      2979|       3582|\n|SIMD2020 Health     |         854|      2540|       3252|\n|SIMD2020 Education  |        2962|      3174|       3913|\n|SIMD2020 Access     |        6030|      4023|       3033|\n|SIMD2020 Crime      |          60|      3511|       4313|\n|SIMD2020 Housing    |        1190|      4071|       4518|\n:::\n:::\n\n\n## Spatial clustering\n\nDeprivation is not distributed randomly across space. If deprived areas tend to cluster together, this creates compounding disadvantage --- residents of a deprived datazone surrounded by other deprived datazones face a concentration effect that isolated pockets of deprivation do not.\n\nWe test for spatial clustering using **Moran's I**, a standard measure of spatial autocorrelation. A positive Moran's I indicates that similar values cluster together (deprived near deprived, affluent near affluent). We run both a *global* test (is there clustering across all of South Ayrshire?) and a *local* test (which specific datazones are part of significant clusters?).\n\n\n::: {.cell}\n\n:::\n\n\n### Global Moran's I\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Global Moran's I test for spatial autocorrelation across South Ayrshire datazones\n\n|Variable            | Moran's I| Z-score|p-value |Significant |\n|:-------------------|---------:|-------:|:-------|:-----------|\n|Rank                |     0.481|    9.47|< 0.001 |Yes         |\n|Income              |     0.464|    9.13|< 0.001 |Yes         |\n|SIMD2020 Employment |     0.440|    8.68|< 0.001 |Yes         |\n|SIMD2020 Health     |     0.444|    8.75|< 0.001 |Yes         |\n|SIMD2020 Education  |     0.503|    9.90|< 0.001 |Yes         |\n|SIMD2020 Access     |     0.646|   12.66|< 0.001 |Yes         |\n|SIMD2020 Crime      |     0.239|    4.76|< 0.001 |Yes         |\n|SIMD2020 Housing    |     0.431|    8.51|< 0.001 |Yes         |\n:::\n:::\n\n\n### Moran scatterplot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Moran scatterplot for overall SIMD rank. Each point is a datazone; the x-axis shows its own rank, the y-axis shows the average rank of its neighbours. Red points are datazones in the wider Ayr study area. The positive slope confirms that deprivation clusters spatially.](simd-ayr-town-centre_files/figure-html/moran-scatter-1.png){width=1500}\n:::\n:::\n\n\n### Local clusters (LISA)\n\nThe **Local Indicators of Spatial Association** (LISA) identify which specific datazones are part of statistically significant clusters:\n\n- **High-High** (hot spots): Deprived datazones surrounded by other deprived datazones --- concentrated disadvantage\n- **Low-Low** (cold spots): Affluent datazones surrounded by other affluent datazones\n- **High-Low / Low-High**: Spatial outliers --- a deprived area in an affluent neighbourhood or vice versa\n\n\n::: {.cell}\n::: {.cell-output-display}\n![LISA cluster map for overall SIMD rank. High-High clusters (red) indicate statistically significant concentrations of deprivation. Low-Low clusters (blue) indicate affluence clusters. Map zoomed to the Wider Ayr study area.](simd-ayr-town-centre_files/figure-html/lisa-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![LISA cluster map across all of South Ayrshire, providing context for how Ayr's clusters relate to the wider council area.](simd-ayr-town-centre_files/figure-html/lisa-full-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Number of datazones in each LISA cluster type, by study area tier\n\n|focus_tier             | Not Significant| High-High| Low-Low| Low-High| High-Low|\n|:----------------------|---------------:|---------:|-------:|--------:|--------:|\n|Town Centre            |               2|         0|       0|        0|        0|\n|Wider Ayr              |              34|         6|      11|        1|        0|\n|Rest of South Ayrshire |              81|        12|       3|        2|        1|\n:::\n:::\n\n\n## Key findings\n\n\n::: {.cell}\n\n:::\n\n\n1. **The town centre is severely deprived.** The two town centre datazones have a mean SIMD rank of 1104 out of 6,976 (decile 2.5), placing them among the most deprived areas in Scotland.\n\n2. **The wider catchment is also disadvantaged.** The Wider Ayr area has a mean rank of 3128 (decile 5), substantially below the rest of South Ayrshire (mean rank 3650). 35% of Wider Ayr datazones fall in the bottom 20% nationally.\n\n3. **Deprivation clusters spatially.** Global Moran's I is positive and highly significant across all domains, confirming that deprived areas are concentrated together rather than scattered. 6 datazones in the Ayr study area form statistically significant deprivation hot spots (High-High clusters).\n\n4. **Domain drivers vary.** The domain profile reveals which aspects of deprivation are most acute in the town centre and its surrounds --- and which domains may present relative strengths. This matters for targeting the [Pride in Place](../docs/reference-summaries/ref-pride-in-place.qmd) investment and the [Burns Statue Square](../docs/reference-summaries/ref-burns-statue-square.qmd) redevelopment.\n\n5. **The vicious cycle is visible in the data.** The co-occurrence of deprivation across Income, Employment, Health, and Housing domains in the town centre and surrounding areas is consistent with the project's core hypothesis: that poor infrastructure, reduced footfall, business closures, and depopulation reinforce each other. The [Hourstons/Arran Mall](../docs/reference-summaries/ref-hourstons-arran-mall.qmd) site --- three failed regeneration plans in six years --- is a concrete manifestation of this pattern.\n\n### Limitations\n\n- **SIMD is area-level, not individual-level.** Not everyone in a deprived datazone is deprived, and not all deprivation in less deprived areas is captured.\n- **SIMD 2020v2 uses pre-pandemic data.** The indicator data largely predates COVID-19; the situation may have worsened since.\n- **Rank-based measures are ordinal.** The difference between rank 100 and rank 200 is not necessarily the same as between rank 3,000 and rank 3,100.\n- **Two datazones is a very small Town Centre.** With only 2 datazones, the \"Town Centre\" tier statistics are inherently noisy. The Wider Ayr tier provides more robust aggregate comparisons.\n- **Datazone boundaries do not align perfectly with functional boundaries.** Ian's definition of the town centre (based on walking distance from parking) is more precise than what 2011 datazone boundaries can capture.\n\n## Next steps\n\n- **Population trends**: How has the demographic profile of these datazones changed over time? Are working-age residents leaving the town centre?\n- **Urban accessibility**: How well connected is Ayr town centre by road, rail, and bus? Does the road network create the pedestrian barriers Ian describes?\n- **Local economy**: What do business counts, vacancy rates, and sectoral employment tell us about the town centre's economic trajectory?\n\n## References\n",
    "supporting": [
      "simd-ayr-town-centre_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}