{
  "hash": "4c584850540b8277a29220c052b45b30",
  "result": {
    "markdown": "---\ntitle: \"The Economic Profile of Ayr Town Centre\"\nsubtitle: \"Employment, Income, and the Case Against Surrender\"\nformat:\n  html:\n    embed-resources: true\n    toc: true\n    toc-depth: 3\n    fig-width: 10\n    fig-height: 8\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n## Introduction\n\nAyr town centre faces a critical choice. After three failed regeneration attempts at the former Hourstons/Arran Mall site --- leisure centre, care village, and now mixed residential [@southayrshire2025hourstons] --- the question is whether to surrender the town centre to residential conversion or to pursue economic renaissance. The Burns Statue Square redevelopment [@southayrshire2025burnsstatue] targets the town centre directly, while the Pride in Place programme [@ukgov2025prideinplace] funds regeneration in Northern Ayr (north of the River Ayr) with potential indirect benefits for the town centre.\n\nThis report examines the economic evidence. Using raw deprivation indicators from the Scottish Index of Multiple Deprivation [@scotgov2020simd] and employment data from the Business Register and Employment Survey [@ons2024bres], we profile the economic base of Ayr town centre and its wider catchment at datazone level.\n\nThe analysis uses the same three-tier geography as the [deprivation report](simd-ayr-town-centre.qmd):\n\n- **Town Centre** (2 datazones): the core walkable retail/hospitality zone\n- **Wider Ayr** (52 datazones): the natural catchment area for Ayr town centre\n- **Rest of South Ayrshire** (99 datazones)\n\n## The working population\n\nBefore examining jobs and businesses, we need to understand who lives in these areas. The SIMD indicators reveal the economic condition of the resident population.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Population composition by study area tier. The town centre has a small resident population relative to the wider catchment.](local-economy_files/figure-html/population-composition-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Population and deprivation by study area tier. Income and employment deprivation rates are means across datazones.\n\n|focus_tier             | Datazones| Population| Working Age| Working Age %| Income Deprived %| Employment Deprived %|\n|:----------------------|---------:|----------:|-----------:|-------------:|-----------------:|---------------------:|\n|Town Centre            |         2|       1620|        1088|          67.2|               0.2|                   0.2|\n|Wider Ayr              |        52|      37913|       22764|          60.0|               0.2|                   0.1|\n|Rest of South Ayrshire |        99|      73147|       43332|          59.2|               0.1|                   0.1|\n:::\n:::\n\n\n### Income and employment deprivation across datazones\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Income deprivation rate by datazone. Each point represents one datazone, ordered from lowest to highest deprivation. Town centre datazones (red) cluster near the most deprived end.](local-economy_files/figure-html/income-dotplot-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Employment deprivation rate by datazone. The pattern mirrors income deprivation, with the town centre and several Wider Ayr datazones showing high employment deprivation.](local-economy_files/figure-html/employment-dotplot-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Relationship between income and employment deprivation. Point size reflects population. The strong positive correlation shows that areas with low incomes also have high worklessness --- both aspects of the same economic weakness.](local-economy_files/figure-html/income-employment-scatter-1.png){width=1500}\n:::\n:::\n\n\n## Employment structure\n\nWhat kinds of jobs exist in and around Ayr town centre? The Business Register and Employment Survey (BRES) provides employment counts by industry sector at datazone level, giving a picture of the town centre's economic function.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Jobs per capita by study area tier. A functioning town centre typically has more jobs than residents. A ratio above 1.0 indicates a net employment hub; below 1.0 indicates a dormitory area.\n\n|Tier                   | Population| Working Age| Total Jobs| Jobs per Resident| Jobs per Working-Age Person|\n|:----------------------|----------:|-----------:|----------:|-----------------:|---------------------------:|\n|Town Centre            |       1620|        1088|       3830|              2.36|                        3.52|\n|Wider Ayr              |      37913|       22764|      12910|              0.34|                        0.57|\n|Rest of South Ayrshire |      73147|       43332|      29135|              0.40|                        0.67|\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Employment composition by sector and tier. The chart shows what proportion of jobs in each tier come from each broad industry sector.](local-economy_files/figure-html/employment-pct-chart-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Absolute employment counts by sector and tier. The wider Ayr catchment has the largest employment base, with health and social care, retail, and hospitality as the dominant sectors.](local-economy_files/figure-html/employment-count-chart-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Top sectors by employment in the Wider Ayr catchment area.](local-economy_files/figure-html/top-sectors-wider-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Employment breakdown for the two town centre datazones. Despite deprivation, the town centre retains a diverse employment base.\n\n|Sector                                     | Employment| Share (%)|\n|:------------------------------------------|----------:|---------:|\n|Retail & wholesale                         |       1250|      32.6|\n|Professional & business services           |        785|      20.5|\n|Hospitality                                |        450|      11.7|\n|Arts, recreation & other services          |        425|      11.1|\n|Transport & storage                        |        300|       7.8|\n|Construction & manufacturing               |        220|       5.7|\n|Health & social care                       |        175|       4.6|\n|Education                                  |        155|       4.0|\n|Public administration                      |         60|       1.6|\n|Other (agriculture, energy, water, mining) |         10|       0.3|\n:::\n:::\n\n\n## Deprivation as economic signal\n\nThe SIMD indicators, examined in the [deprivation report](simd-ayr-town-centre.qmd) as measures of disadvantage, can also be read as economic signals. Each indicator tells us something about the viability of the town centre as an economic space.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Economic health profile by tier. Each bar shows where the tier's mean falls in the national distribution (percentile). Values above the dashed line (50th percentile) indicate a worse position than the national median. The Town Centre and Wider Ayr areas score poorly across most indicators.](local-economy_files/figure-html/health-profile-chart-1.png){width=1350}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Economic health indicators by tier. Values shown with national percentile position in brackets. Higher percentile = worse national position.\n\n|Indicator                  |Town Centre          |Wider Ayr           |Rest of SA          |\n|:--------------------------|:--------------------|:-------------------|:-------------------|\n|Income deprivation         |0.2 (82.3th %ile)    |0.2 (69.2th %ile)   |0.1 (53th %ile)     |\n|Employment deprivation     |0.2 (89.8th %ile)    |0.1 (70.9th %ile)   |0.1 (53.9th %ile)   |\n|Crime rate                 |1677.7 (99.1th %ile) |346.8 (71.5th %ile) |191.5 (45.5th %ile) |\n|Overcrowding               |0.2 (80.1th %ile)    |0.1 (50.8th %ile)   |0.1 (40.3th %ile)   |\n|No central heating         |0 (83th %ile)        |0 (34.8th %ile)     |0 (42.8th %ile)     |\n|Comparative Illness Factor |150 (80th %ile)      |119 (64.4th %ile)   |93.5 (51.5th %ile)  |\n|Alcohol hospitalisations   |313.7 (96th %ile)    |131.6 (73.5th %ile) |89.7 (58.7th %ile)  |\n|Drug hospitalisations      |303.3 (92.6th %ile)  |189.3 (83.9th %ile) |81.8 (62.4th %ile)  |\n:::\n:::\n\n\n### What the indicators mean for economic viability\n\n- **Income deprivation** signals low consumer spending power. Businesses in high-deprivation areas face a smaller effective market --- residents have less disposable income to spend locally.\n\n- **Employment deprivation** reflects both fewer potential customers (unemployed people spend less) and a signal of labour market weakness. However, it also represents a potential workforce that could be engaged through targeted employment initiatives.\n\n- **Crime** affects the business environment through insurance costs, security spending, staff retention, and --- most critically --- deterring visitors and footfall.\n\n- **Health indicators** (illness, alcohol, drug hospitalisations) represent demand for health services. This supports the case for anchoring GP surgeries, pharmacies, addiction services, and community health facilities in the town centre rather than dispersing them.\n\n- **Housing quality** (overcrowding, no central heating) challenges the argument for more residential conversion. If existing housing stock is poor, the priority should be improving what exists rather than adding more of the same.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relationship between income deprivation and crime rate across South Ayrshire datazones. The correlation reinforces the vicious cycle: areas with lower incomes tend to have higher crime, which in turn deters business and investment.](local-economy_files/figure-html/crime-income-scatter-1.png){width=1500}\n:::\n:::\n\n\n### Health service demand\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Health indicators by tier (higher values = greater need). CIF = Comparative Illness Factor, SMR = Standardised Mortality Ratio. These are standardised measures where 100 = Scottish average. Values above 100 indicate greater need than the national norm.\n\n|Tier                   | Illness (CIF)| Mortality (SMR)| Alcohol| Drug| Emergency| Depression %|\n|:----------------------|-------------:|---------------:|-------:|----:|---------:|------------:|\n|Town Centre            |           150|             109|     314|  303|       167|          0.3|\n|Wider Ayr              |           119|             107|     132|  189|       138|          0.2|\n|Rest of South Ayrshire |            93|              89|      90|   82|       119|          0.2|\n:::\n:::\n\n\nThe elevated health indicators in the Town Centre and Wider Ayr tiers represent concentrated demand for health services. Locating health facilities within walking distance of these populations would both serve clinical need and generate town centre footfall --- a virtuous rather than vicious cycle.\n\n## Access to services\n\nThe SIMD access domain measures travel times to key services by car and public transport. The gap between these two modes reveals how car-dependent the area is --- a critical consideration given that the most deprived residents are least likely to own a car.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Mean travel time to GP, post office, and retail centre by mode and tier. The gap between drive time and public transport time indicates car dependency. For the town centre, travel times are naturally low; for Wider Ayr, the PT gap reveals accessibility challenges.](local-economy_files/figure-html/access-chart-1.png){width=1500}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Mean access indicators by tier. Travel times in minutes. Broadband = % of premises with high-speed access.\n\n|Indicator                 | Town Centre| Wider Ayr| Rest of SA|\n|:-------------------------|-----------:|---------:|----------:|\n|drive_petrol              |         2.8|       2.5|        3.9|\n|Drive to GP               |         1.8|       3.1|        3.7|\n|Drive to Post Office      |         2.0|       2.7|        3.1|\n|Drive to Primary School   |         2.9|       2.9|        3.2|\n|Drive to Retail           |         2.4|       4.4|        5.5|\n|Drive to Secondary School |         2.9|       4.1|        6.5|\n|PT to GP                  |         4.6|       9.0|       11.3|\n|PT to Post Office         |         5.3|       7.8|        9.6|\n|PT to Retail              |         6.8|      11.2|       13.8|\n|Broadband access          |         0.0|       0.0|        0.1|\n:::\n:::\n\n\nThis section provides a preview of the access dimension; a full accessibility analysis examining road network design, pedestrian infrastructure, and public transport connectivity is planned as a subsequent report.\n\n## The economic case\n\n\n::: {.cell}\n\n:::\n\n\n### The case against surrender\n\nThe evidence does not support converting the town centre to predominantly residential use:\n\n1. **The town centre still functions as an employment hub.** With 3,830 jobs for 1,620 residents (2.36 jobs per resident), the town centre has more employment than population. Converting it to residential use would destroy this employment base.\n\n2. **More residents will not solve the spending power problem.** With an income deprivation rate of 0% in the town centre and 0% in the wider catchment (compared to 0% in the rest of South Ayrshire), adding more residents to the most income-deprived area will not increase consumer spending --- it will dilute it further.\n\n3. **Employment deprivation compounds the problem.** With 0% employment deprivation in the town centre, new residential development would house people in an area where 0 in every 100 working-age adults already cannot find work.\n\n4. **Crime deters investment and footfall.** The town centre's crime rate of NA per capita signals an environment that discourages both commercial tenants and visitors. Residential conversion without addressing crime merely relocates vulnerable people into a high-crime environment.\n\n5. **Housing quality questions remain.** Existing housing in the area already shows elevated overcrowding and poor heating. Adding more residential stock without addressing these systemic issues is not regeneration --- it is managed decline.\n\n### The case for renaissance\n\nThe same evidence points toward a viable alternative:\n\n1. **Health services should be anchored in the town centre.** With a Comparative Illness Factor of 150 in the town centre and 119 in the wider catchment (Scottish average = 100), there is clear demand for health services in these areas. GP surgeries, pharmacies, and community health facilities generate consistent footfall and create a reason for regular visits to the town centre.\n\n2. **The employment base, though weakened, is diverse.** Retail, hospitality, health, education, and professional services all have a presence. The Pride in Place programme (up to \\pounds{}20 million over 10 years) and Burns Statue Square redevelopment (\\pounds{}16 million) create an investment window to strengthen rather than abandon this base.\n\n3. **Education and skills represent an opportunity.** High rates of no qualifications and low university participation indicate unmet demand for education and training --- exactly the kind of service that could be anchored in a town centre, drawing people in and building human capital.\n\n4. **The catchment population exists.** The Wider Ayr area has a substantial residential population. The challenge is not a lack of people but a lack of reasons --- and accessible routes --- to come into the town centre.\n\n### Summary\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Key economic statistics for Ayr town centre and policy implications\n\n|Indicator                                        |Value           |Implication                                                                  |\n|:------------------------------------------------|:---------------|:----------------------------------------------------------------------------|\n|Town centre population                           |1,620           |Small residential base --- town centre functions as workplace, not dormitory |\n|Town centre jobs                                 |3,830           |Significant employment hub despite deprivation                               |\n|Jobs per resident                                |2.36            |More jobs than residents: town centre serves wider area                      |\n|Income deprivation (Town Centre)                 |0%              |Low spending power among residents                                           |\n|Income deprivation (Wider Ayr)                   |0%              |Low spending power across entire catchment                                   |\n|Employment deprivation (Town Centre)             |0%              |High worklessness limits local economic activity                             |\n|Crime rate (Town Centre)                         |NA              |Deters footfall and business investment                                      |\n|Illness factor (Town Centre, Scottish avg = 100) |150             |High health service demand --- anchor services here                          |\n|Illness factor (Wider Ayr, Scottish avg = 100)   |119             |Catchment-wide health need supports service co-location                      |\n|Pride in Place investment                        |£20m / 10 years |Opportunity window for economic regeneration                                 |\n|Burns Statue Square investment                   |£16m            |Physical infrastructure investment creates momentum                          |\n:::\n:::\n\n\n### Limitations\n\n- **BRES open access data is rounded** to the nearest 5 for disclosure control. Small-area employment counts should be interpreted as approximate.\n- **SIMD 2020v2 uses pre-pandemic data** (approximately 2017--2019). Employment and income deprivation may have worsened since.\n- **BRES data covers employees**, not self-employed workers. Town centre self-employment (e.g. market traders, independent retailers) is not captured.\n- **Only two town centre datazones** makes tier-level statistics inherently noisy. Individual datazone values should be examined alongside tier averages.\n- **Correlation is not causation.** The scatter plots show associations between indicators, not causal relationships.\n\n## References\n",
    "supporting": [
      "local-economy_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}