{
  "hash": "15dbf88ff8f7d1203de44232dc9b04a3",
  "result": {
    "markdown": "---\ntitle: \"Demographic Profile of South Ayrshire\"\nsubtitle: \"Comparison with Scottish Council Areas\"\nformat:\n  html:\n    embed-resources: true\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n:::\n\n\n# Introduction\n\nThis analysis examines the demographic profile of South Ayrshire in the context of all 32 Scottish council areas. It forms part of the evidence base for the [Revitalising Ayr Town Centre](../docs/background.qmd) project, which hypothesises that population ageing and depopulation are contributing to a vicious cycle of town centre decline.\n\nThe key questions are:\n\n- **Is South Ayrshire ageing faster than comparable areas?**\n- **Which council areas are most demographically similar?**\n- **Where does South Ayrshire sit relative to Scotland as a whole?**\n\nData source: NRS mid-year population estimates [@nrs2024population] (2024), single year of age by sex, for all 32 council areas and Scotland.\n\n# South Ayrshire's Population Structure\n\nSouth Ayrshire has a total population of **112,260** and a median age of **49.2** years, compared to Scotland's median of **41.8** years.\n\nThe population pyramid below shows South Ayrshire's age-sex distribution (coloured bars) against the Scotland average (dark outline). The comparison uses proportions of total population so that areas of different sizes are directly comparable.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](demographic-comparison_files/figure-html/pyramid-1.png){width=768}\n:::\n:::\n\n\n# Indicator Rankings\n\nThe table below summarises key demographic indicators for South Ayrshire, with its rank among all 33 areas (32 councils + Scotland). Rank 1 = highest value.\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: South Ayrshire demographic indicators (2024)\n\n|Indicator                            |South Ayrshire |Scotland | Rank|\n|:------------------------------------|:--------------|:--------|----:|\n|Median age                           |49.2           |41.8     |    5|\n|Old-age dependency ratio (65+/16-64) |47.3%          |32.4%    |    4|\n|Child dependency ratio (0-15/16-64)  |25.8%          |25.5%    |   23|\n|Working-age proportion (16-64)       |57.8%          |63.3%    |   30|\n|Proportion aged 65+                  |27.3%          |20.5%    |    5|\n|Proportion aged 75+                  |13.2%          |9.5%     |    4|\n:::\n:::\n\n\n## Median Age\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](demographic-comparison_files/figure-html/median-age-chart-1.png){width=768}\n:::\n:::\n\n\n## Old-Age Dependency Ratio\n\nThe old-age dependency ratio measures the number of people aged 65+ per person of working age (16–64). A higher ratio implies greater pressure on services and a smaller economically active population.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](demographic-comparison_files/figure-html/dep-ratio-chart-1.png){width=768}\n:::\n:::\n\n\n## Proportion Aged 75+\n\nThis indicator captures \"deep ageing\" — the proportion of the population in the oldest age groups, who are most likely to need intensive health and care services.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](demographic-comparison_files/figure-html/prop-75-chart-1.png){width=768}\n:::\n:::\n\n\n# Most Similar Council Areas\n\nTo identify which council areas are most demographically similar to South Ayrshire, six indicators were standardised (z-scored) and Euclidean distance was calculated in this standardised space. The indicators used are: median age, old-age dependency ratio, child dependency ratio, working-age proportion, age distribution spread (SD), and proportion aged 75+.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](demographic-comparison_files/figure-html/similarity-chart-1.png){width=768}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Top 10 most demographically similar council areas to South Ayrshire\n\n|Council Area          | Population| Median Age|Old-Age Dep. |Working Age % |75+ % | Distance|\n|:---------------------|----------:|----------:|:------------|:-------------|:-----|--------:|\n|Scottish Borders      |     116980|       49.9|47.7%        |57.4%         |13.2% |     0.32|\n|Dumfries and Galloway |     145860|       50.5|49.0%        |57.2%         |13.5% |     0.49|\n|Na h-Eileanan Siar    |      26020|       50.5|47.2%        |58.0%         |13.1% |     0.56|\n|Orkney Islands        |      22020|       48.6|44.1%        |58.6%         |12.6% |     0.69|\n|Angus                 |     114810|       47.7|44.2%        |58.5%         |12.7% |     0.72|\n|Argyll and Bute       |      87690|       50.7|47.5%        |58.4%         |13.2% |     0.96|\n|Perth and Kinross     |     154420|       46.8|42.4%        |59.3%         |12.2% |     1.11|\n|Highland              |     237290|       47.1|41.1%        |59.9%         |11.5% |     1.54|\n|North Ayrshire        |     134010|       47.0|41.2%        |59.8%         |11.3% |     1.57|\n|Moray                 |      95010|       45.4|39.1%        |60.3%         |11.1% |     2.01|\n:::\n:::\n\n\n## Population Pyramids: South Ayrshire and Most Similar Areas\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](demographic-comparison_files/figure-html/pyramid-comparison-1.png){width=960}\n:::\n:::\n\n\n# Key Findings\n\n\n::: {.cell}\n\n:::\n\n\n- **South Ayrshire is substantially older than Scotland as a whole.** Its median age (49.2) is 7.4 years above the national median (41.8), ranking 5th oldest of 33 areas.\n\n- **The old-age dependency ratio is among the highest in Scotland** (rank 4), meaning South Ayrshire has proportionally more people aged 65+ relative to its working-age population than most other council areas.\n\n- **The most demographically similar areas** are Scottish Borders, Dumfries and Galloway, Na h-Eileanan Siar. These share South Ayrshire's pattern of an ageing population with a relatively small working-age base.\n\n- **These findings are consistent with the project's theory of change**: an ageing and shrinking population weakens the economic base, contributing to the decline cycle identified in the [project background](../docs/background.qmd).\n\n- **Next steps**: examine population *trends* over time (not just the current snapshot), investigate migration flows, and layer in economic indicators (vacancy rates, footfall) to understand whether the demographic structure is accelerating town centre decline.\n\n## References\n",
    "supporting": [
      "demographic-comparison_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}